    // string tc;
    // getline(cin, tc);
    //     string s ,ch;
    //     getline(cin, s);
    //     Node* root = buildTree(s);
    //     Solution ob;
    //     vector <int> res = ob.bottomView(root);
    //     for (int i : res) cout << i << " ";
    //     cout << endl;
    // return 0;